serenity.report.encoding = UTF-8

webdriver.base.url=https://www.saucedemo.com/

webdriver.driver=chrome
chrome.switches=--incognito,--disable-notifications,--window-size=800,500,--disable-save-password-bubble,--disable-credentials-enable-service,--password-store=basic,--no-default-browser-check,--disable-autofill-keyboard-accessory-view,--disable-autofill
